// Mocks generated by Mockito 5.4.5 from annotations
// in eventify/test/unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:eventify/data/services/api_client.dart' as _i2;
import 'package:eventify/models/category_model.dart' as _i12;
import 'package:eventify/models/comment_model.dart' as _i13;
import 'package:eventify/models/event_model.dart' as _i5;
import 'package:eventify/models/event_summary_model.dart' as _i11;
import 'package:eventify/models/follow_user_model.dart' as _i14;
import 'package:eventify/models/location_model.dart' as _i9;
import 'package:eventify/models/notification_model.dart' as _i10;
import 'package:eventify/models/social_interactions.dart' as _i7;
import 'package:eventify/models/user_model.dart' as _i8;
import 'package:eventify/utils/result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  @override
  _i3.Future<_i4.Result<List<_i5.EventModel>>> getEvents(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [userId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.EventModel>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.EventModel>>>(
                this,
                Invocation.method(#getEvents, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i5.EventModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.EventModel>>>(
                    this,
                    Invocation.method(#getEvents, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.EventModel>>>);

  @override
  _i3.Future<_i4.Result<_i7.SocialInteractions>> likeEvent(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeEvent, [eventId, userId]),
            returnValue: _i3.Future<_i4.Result<_i7.SocialInteractions>>.value(
              _i6.dummyValue<_i4.Result<_i7.SocialInteractions>>(
                this,
                Invocation.method(#likeEvent, [eventId, userId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i7.SocialInteractions>>.value(
                  _i6.dummyValue<_i4.Result<_i7.SocialInteractions>>(
                    this,
                    Invocation.method(#likeEvent, [eventId, userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i7.SocialInteractions>>);

  @override
  _i3.Future<_i4.Result<List<_i5.EventModel>>> searchEvents(
    String? query,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchEvents, [query, userId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.EventModel>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.EventModel>>>(
                this,
                Invocation.method(#searchEvents, [query, userId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i5.EventModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.EventModel>>>(
                    this,
                    Invocation.method(#searchEvents, [query, userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.EventModel>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.UserModel>>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i3.Future<_i4.Result<List<_i8.UserModel>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.UserModel>>>(
                this,
                Invocation.method(#searchUsers, [query]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i8.UserModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#searchUsers, [query]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.UserModel>>>);

  @override
  _i3.Future<_i4.Result<void>> createEvent({
    required String? userId,
    required String? eventImage,
    required int? categoryId,
    required String? locationId,
    required String? title,
    required String? description,
    required DateTime? date,
    required DateTime? startsAt,
    required DateTime? endsAt,
    String? eventMusic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEvent, [], {
              #userId: userId,
              #eventImage: eventImage,
              #categoryId: categoryId,
              #locationId: locationId,
              #title: title,
              #description: description,
              #date: date,
              #startsAt: startsAt,
              #endsAt: endsAt,
              #eventMusic: eventMusic,
            }),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#createEvent, [], {
                  #userId: userId,
                  #eventImage: eventImage,
                  #categoryId: categoryId,
                  #locationId: locationId,
                  #title: title,
                  #description: description,
                  #date: date,
                  #startsAt: startsAt,
                  #endsAt: endsAt,
                  #eventMusic: eventMusic,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#createEvent, [], {
                  #userId: userId,
                  #eventImage: eventImage,
                  #categoryId: categoryId,
                  #locationId: locationId,
                  #title: title,
                  #description: description,
                  #date: date,
                  #startsAt: startsAt,
                  #endsAt: endsAt,
                  #eventMusic: eventMusic,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i9.LocationModel>> createLocation({
    required String? latitude,
    required String? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLocation, [], {
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i3.Future<_i4.Result<_i9.LocationModel>>.value(
              _i6.dummyValue<_i4.Result<_i9.LocationModel>>(
                this,
                Invocation.method(#createLocation, [], {
                  #latitude: latitude,
                  #longitude: longitude,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i9.LocationModel>>.value(
                  _i6.dummyValue<_i4.Result<_i9.LocationModel>>(
                    this,
                    Invocation.method(#createLocation, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.LocationModel>>);

  @override
  _i3.Future<_i4.Result<List<_i10.NotificationModel>>> getNotifications(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [userId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i10.NotificationModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i10.NotificationModel>>>(
                    this,
                    Invocation.method(#getNotifications, [userId]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i10.NotificationModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i10.NotificationModel>>>(
                    this,
                    Invocation.method(#getNotifications, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i10.NotificationModel>>>);

  @override
  _i3.Future<_i4.Result<void>> registerUser(_i8.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [user]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#registerUser, [user]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#registerUser, [user]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.EventModel>> getEventDetails(
    String? eventId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEventDetails, [eventId, userId]),
            returnValue: _i3.Future<_i4.Result<_i5.EventModel>>.value(
              _i6.dummyValue<_i4.Result<_i5.EventModel>>(
                this,
                Invocation.method(#getEventDetails, [eventId, userId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i5.EventModel>>.value(
                  _i6.dummyValue<_i4.Result<_i5.EventModel>>(
                    this,
                    Invocation.method(#getEventDetails, [eventId, userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.EventModel>>);

  @override
  _i3.Future<_i4.Result<_i8.UserModel>> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i3.Future<_i4.Result<_i8.UserModel>>.value(
              _i6.dummyValue<_i4.Result<_i8.UserModel>>(
                this,
                Invocation.method(#getUser, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i8.UserModel>>.value(
                  _i6.dummyValue<_i4.Result<_i8.UserModel>>(
                    this,
                    Invocation.method(#getUser, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.UserModel>>);

  @override
  _i3.Future<_i4.Result<List<_i11.EventSummaryModel>>> getUserEvents(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserEvents, [userId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i11.EventSummaryModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i11.EventSummaryModel>>>(
                    this,
                    Invocation.method(#getUserEvents, [userId]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i11.EventSummaryModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i11.EventSummaryModel>>>(
                    this,
                    Invocation.method(#getUserEvents, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.EventSummaryModel>>>);

  @override
  _i3.Future<_i4.Result<_i8.UserModel>> updateProfile(_i8.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [user]),
            returnValue: _i3.Future<_i4.Result<_i8.UserModel>>.value(
              _i6.dummyValue<_i4.Result<_i8.UserModel>>(
                this,
                Invocation.method(#updateProfile, [user]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i8.UserModel>>.value(
                  _i6.dummyValue<_i4.Result<_i8.UserModel>>(
                    this,
                    Invocation.method(#updateProfile, [user]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.UserModel>>);

  @override
  _i3.Future<_i4.Result<List<_i12.CategoryModel>>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i3.Future<_i4.Result<List<_i12.CategoryModel>>>.value(
              _i6.dummyValue<_i4.Result<List<_i12.CategoryModel>>>(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i12.CategoryModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i12.CategoryModel>>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i12.CategoryModel>>>);

  @override
  _i3.Future<_i4.Result<List<_i13.CommentModel>>> getComments(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [eventId]),
            returnValue: _i3.Future<_i4.Result<List<_i13.CommentModel>>>.value(
              _i6.dummyValue<_i4.Result<List<_i13.CommentModel>>>(
                this,
                Invocation.method(#getComments, [eventId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i13.CommentModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i13.CommentModel>>>(
                    this,
                    Invocation.method(#getComments, [eventId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i13.CommentModel>>>);

  @override
  _i3.Future<_i4.Result<void>> submitComment(
    String? eventId,
    String? userId,
    _i13.CommentModel? comment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitComment, [eventId, userId, comment]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#submitComment, [eventId, userId, comment]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#submitComment, [eventId, userId, comment]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> sendNotification(
    String? toNotificationToken,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendNotification, [toNotificationToken, data]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#sendNotification, [
                  toNotificationToken,
                  data,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#sendNotification, [
                  toNotificationToken,
                  data,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<String?> getNotificationToken(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationToken, [userId]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i4.Result<void>> updateNotificationToken(
    String? userId,
    String? notificationToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotificationToken, [
              userId,
              notificationToken,
            ]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateNotificationToken, [
                  userId,
                  notificationToken,
                ]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateNotificationToken, [
                  userId,
                  notificationToken,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i14.FollowUserModel>> isFollowing(
    String? userId,
    String? targetUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [userId, targetUserId]),
            returnValue: _i3.Future<_i4.Result<_i14.FollowUserModel>>.value(
              _i6.dummyValue<_i4.Result<_i14.FollowUserModel>>(
                this,
                Invocation.method(#isFollowing, [userId, targetUserId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i14.FollowUserModel>>.value(
                  _i6.dummyValue<_i4.Result<_i14.FollowUserModel>>(
                    this,
                    Invocation.method(#isFollowing, [userId, targetUserId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i14.FollowUserModel>>);

  @override
  _i3.Future<_i4.Result<void>> createNotification(
    _i10.NotificationModel? notificationData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNotification, [notificationData]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#createNotification, [notificationData]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#createNotification, [notificationData]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> followUser(
    String? targetUserId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [targetUserId, userId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#followUser, [targetUserId, userId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#followUser, [targetUserId, userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> unfollowUser(
    String? targetUserId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [targetUserId, userId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#unfollowUser, [targetUserId, userId]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#unfollowUser, [targetUserId, userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i14.FollowUserModel>>> getFollowed(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowed, [userId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i14.FollowUserModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i14.FollowUserModel>>>(
                    this,
                    Invocation.method(#getFollowed, [userId]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i14.FollowUserModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i14.FollowUserModel>>>(
                    this,
                    Invocation.method(#getFollowed, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i14.FollowUserModel>>>);

  @override
  _i3.Future<_i4.Result<List<_i14.FollowUserModel>>> getFollowers(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i14.FollowUserModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i14.FollowUserModel>>>(
                    this,
                    Invocation.method(#getFollowers, [userId]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i14.FollowUserModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i14.FollowUserModel>>>(
                    this,
                    Invocation.method(#getFollowers, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i14.FollowUserModel>>>);

  @override
  _i3.Future<_i4.Result<void>> updateEvent(
    String? eventId,
    _i5.EventModel? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [eventId, event]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateEvent, [eventId, event]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateEvent, [eventId, event]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
